return {
	["specified"] = "specified",
	["teh"] = "the",
	["comparing"] = "comparing",
	["identified"] = "identified",
	["balues"] = "values",
	["compyute"] = "compute",
	["inteacting"] = "interacting",
	["comparison"] = "comparison",
	["internet"] = "internet",
	["databse"] = "database",
	["continues"] = "continues",
	["databses"] = "databases",
	["byte"] = "byte",
}
